### ISSUE TITLE
Glider.js dot colors are harcoded

### ISSUE THREAD

**Issue by merinofg** [thebakerdev/zenii#5]
Glider.js dot colors are harcoded in the CSS meaning that no matter what color user define on tailwind.config.js or on the configuration from October, dots will be always displayed as _soft-purple_.

**Comment by thebakerdev** [comment]
Fixed in [971afcb](https://github.com/thebakerdev/zenii/commit/971afcb398a8930645c55fc2de64140b92acabce). Removed the hardcoded values.
